### ISSUE TITLE
Install on anacinda Python 3.5?

### ISSUE THREAD

**Issue by lovechang1986** [ilastik/marching_cubes#1]
not support Python 3.5?

**Comment by akreshuk** [comment]
It does work on Python 3.6, but we haven't put the package up yet. Thanks for the reminder.

**Comment by lovechang1986** [comment]
Thanks, I saw the example that sample.npy only contain 0 and 1. How to solve question that  if I want to get anthother value of volume data(range from 0 to 100)?

**Comment by stuarteberg** [comment]
You can find pre-built packages for python 3.6 on this channel:

https://anaconda.org/flyem-forge/marching_cubes/files

>sample.npy only contain 0 and 1. How to solve question that if I want to get anthother value of volume data(range from 0 to 100)?

```python
marching_cubes.march(my_array == 50, 0)
```

Also, `scikit-image` has a marching cubes implementation:

```python
from skimage.measure import marching_cubes_lewiner
vertices, faces, normals, values = marching_cubes_lewiner(my_array, 50)
```

**Comment by stuarteberg** [comment]
Uploaded packages to the `ilastik-forge` channel for python 3.5 and 3.6.

```bash
conda install -c ilastik-forge marching_cubes
```
