### ISSUE TITLE
How to install on python 2.7

### ISSUE THREAD

**Issue by li-zemin** [ilastik/marching_cubes#14]
Hello, thank you for your sharing, I would like to install in python2.7 via pip, is there any method?

**Comment by DerThorsten** [comment]
nope, it has a camke/conda based build system

**Comment by adityabalu** [comment]
Look for the recent pull request, now you can install it via pip... 
git clone https://github.com/ilastik/marching_cubes.git 
pip install marching_cubes/
let me know if you face any issues

**Comment by MayuOshima** [comment]
> Look for the recent pull request, now you can install it via pip...
> git clone https://github.com/ilastik/marching_cubes.git
> pip install marching_cubes/
> let me know if you face any issues

Hello, when I use the two command:
```
git clone https://github.com/ilastik/marching_cubes.git
pip install marching_cubes/
```
it says 
`Directory 'marching_cubes/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by DerThorsten** [comment]
* we use cmake / conda  based installation not setup.py
* python2.7 is dead
