### ISSUE TITLE
project genration issue using cmake

### ISSUE THREAD

**Issue by isantos85** [ilastik/marching_cubes#22]
Hello Team,
I am trying to generate VS project using cmake, i am getting pybind11_DIR-NOTFOUND issue with below details:
"CMake Error at CMakeLists.txt:23 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed."

please assist me to generate the project.

**Comment by DerThorsten** [comment]
You need to install pybind11 and point cmake to the directories of pybind11 (good chances that pybind11 is found by default if you have it installed)
Even easier, just use conda to install this package
