### ISSUE TITLE
VTK information on the Readme

### ISSUE THREAD

**Issue by CharlesGueunet** [ilastik/marching_cubes#31]
Hello,

It is written in the Readme that VTK does not support Python 3.X.
This is not true, VTK support Python 3.X depending on its release date:
* VTK 7 supported Python 3.2 to 3.5
* ...
* VTK 9.1 supports Python 3.5 to 3.8

PS. VTK has a [Pypi package](https://pypi.org/project/vtk/) and [wheel files](https://vtk.org/download/)

Can you fix the Readme please ?

**Comment by k-dominik** [comment]
Sure thing, thanks for the heads up, we'll say that at the time of writing, vtk did not support Python 3.

**Comment by k-dominik** [comment]
let me know if you think something could be added to #32
