### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tingzhao** [ilastik/marching_cubes#5]
What's the license of this library? We're planning to use the source code in our project (https://github.com/janelia-flyem/NeuTu/tree/develop).

**Comment by akreshuk** [comment]
I'd make the license BSD, but I'll leave the final decision to @stuarteberg who contributed more than I have.

**Comment by stuarteberg** [comment]
FWIW, I've contributed only build fixes and conda packaging.  @nielsbuwen wrote the majority of the code, with a few bug fixes by @DerThorsten.  But yeah, I think we should go with BSD.  To that end, I've created PR #6.  Somebody click merge if you second this motion.
